WORKING_PATH: test/
THREADS: 12
PARAMETERS:
    PRIMER_SPECIFICITY_DATABASE: nt
    SEARCH_SPECIFIC_PRIMER: True
    PRIMER_PRODUCT_MIN: 500
    PRIMER_PRODUCT_MAX: 3000
    PRIMER_NUM_RETURN: 10
    PRIMER_MIN_TM: 57.0
    PRIMER_OPT_TM: 60.0
    PRIMER_MAX_TM: 63.0
    PRIMER_MAX_DIFF_TM: 3
    PRIMER_ON_SPLICE_SITE: 0
    SPLICE_SITE_OVERLAP_5END: 7
    SPLICE_SITE_OVERLAP_3END: 4
    SPLICE_SITE_OVERLAP_3END_MAX: 8
    MIN_INTRON_SIZE: 1000
    MAX_INTRON_SIZE: 1000000
    SEARCH_SPECIFIC_PRIMER: checked
    SEARCHMODE: 0
    PRIMER_SPECIFICITY_MISMATCH: 1
    PRIMER_3END_SPECIFICITY_MISMATCH: 1
    MISMATCH_REGION_LENGTH: 5
    TOTAL_MISMATCH_IGNORE: 6
    MAX_TARGET_SIZE: 4000
    HITSIZE: 100000
    EVALUE: 30000
    WORD_SIZE: 7
    MAX_CANDIDATE_PRIMER: 500
    NUM_TARGETS: 20
    NUM_TARGETS_WITH_PRIMERS: 10000
    MAX_TARGET_PER_TEMPLATE: 100000
    PRIMER_MIN_SIZE: 15
    PRIMER_OPT_SIZE: 20
    PRIMER_MAX_SIZE: 25
    PRIMER_MIN_GC: 20.0
    PRIMER_MAX_GC: 80.0
    GC_CLAMP: 0
    POLYX: 5
    PRIMER_MAX_END_STABILITY: 9
    PRIMER_MAX_END_GC: 5
    PRIMER_MAX_TEMPLATE_MISPRIMING_TH: 40.00
    PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH: 70.00
    PRIMER_MAX_SELF_ANY_TH: 45.0
    PRIMER_MAX_SELF_END_TH: 35.0
    PRIMER_PAIR_MAX_COMPL_ANY_TH: 45.0
    PRIMER_PAIR_MAX_COMPL_END_TH: 35.0
    PRIMER_MAX_HAIRPIN_TH: 24.0
    PRIMER_MAX_TEMPLATE_MISPRIMING: 12.00
    PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING: 24.00
    SELF_ANY: 8.00
    SELF_END: 3.00
    PRIMER_PAIR_MAX_COMPL_ANY: 8.00
    PRIMER_PAIR_MAX_COMPL_END: 3.00
    OVERLAP_5END: 7
    OVERLAP_3END: 4
    MONO_CATIONS: 50.0
    DIVA_CATIONS: 1.5
    CON_DNTPS: 0.6
    SALT_FORMULAR: 1
    TM_METHOD: 1
    CON_ANEAL_OLIGO: 50.0
    PRIMER_MISPRIMING_LIBRARY: AUTO
    LOW_COMPLEXITY_FILTER: checked
    PRIMER_INTERNAL_OLIGO_MIN_SIZE: 18
    PRIMER_INTERNAL_OLIGO_OPT_SIZE: 20
    PRIMER_INTERNAL_OLIGO_MAX_SIZE: 27
    PRIMER_INTERNAL_OLIGO_MIN_TM: 57.0
    PRIMER_INTERNAL_OLIGO_OPT_TM: 60.0
    PRIMER_INTERNAL_OLIGO_MAX_TM: 63.0
    PRIMER_INTERNAL_OLIGO_MIN_GC: 20.0
    PRIMER_INTERNAL_OLIGO_OPT_GC_PERCENT: 50
    PRIMER_INTERNAL_OLIGO_MAX_GC: 80.0